/**:
  ros__parameters:
    left_wheel_signal:
      type: axis
      index: 1                    # Left Stick
    right_wheel_signal:
      type: axis
      index: 4                    # Right Stick
    raise_front_arm_signal:
      type: button
      index: 5                    # R1
    lower_front_arm_signal:
      type: axis
      index: 5                    # R2
      accept: -1.0
    raise_back_arm_signal:
      type: button
      index: 4                    # L1
    lower_back_arm_signal:
      type: axis
      index: 2                    # L2
      accept: -1.0
    dig_front_drum_signal:
      type: button
      index: 1                    # Circle
    dump_front_drum_signal:
      type: button
      index: 2                    # Triangle
    dig_back_drum_signal:
      type: button
      index: 0                    # Cross
    dump_back_drum_signal:
      type: button
      index: 3                    # Square
    auto_dock_routine_signal:
      type: axis
      index: 7                    # D-Pad Up
      accept: -1.0
    auto_drive_routine_signal:
      type: axis
      index: 7                    # D-Pad Down
      accept: 1.0
    auto_dig_routine_signal:
      type: axis
      index: 6                    # D-Pad Right
      accept: 1.0
    auto_dump_routine_signal:
      type: axis
      index: 6                    # D-Pad Left
      accept: -1.0
    full_autonomy_routine_signal:
      type: button
      index: 9                    # Options
    stop_routine_signal:
      type: button
      index: 8                    # Share
